# Part D - the alternative version generated by AI.
# The function itself is kept UNMODIFIED, so the comparison in Part E is honest.
# The calls at the bottom were added only so the file demonstrates its behaviour.

from datetime import datetime

appointments = []


def add_appointment(patient_name, practitioner_name, appointment_time):
    appointment = {
        "patient_name": patient_name,
        "practitioner_name": practitioner_name,
        "appointment_time": datetime.strptime(appointment_time, "%Y-%m-%d %H:%M"),
        "status": "confirmed"
    }
    appointments.append(appointment)
    print("Appointment booked successfully!")
    return appointment


if __name__ == "__main__":
    # Test 1: the sample data used everywhere else in this assignment.
    print("Test 1 - the handout's own sample time format:")
    try:
        add_appointment('Alice Smith', 'Dr. John Doe', '2024-07-20 10:00 AM')
    except ValueError as error:
        print(f"  ValueError: {error}")

    # Test 2: the format its own strptime call expects.
    print("\nTest 2 - the 24-hour format its format string expects:")
    try:
        add_appointment('Bob Johnson', 'Dr. Jane Roe', '2024-07-20 11:30')
    except ValueError as error:
        print(f"  ValueError: {error}")

    # Test 3: an empty patient name - the one check the human version has.
    print("\nTest 3 - empty patient name:")
    try:
        add_appointment('', 'Dr. Jane Roe', '2024-07-20 13:00')
        print("  Accepted - no validation of the patient name at all.")
    except ValueError as error:
        print(f"  ValueError: {error}")